import { useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { admin, catalogue, volunteer, works, type WorkDetail, type BookUpdateIn } from "../../lib/api";
import { useAuth } from "../../hooks/useAuth";
import EntityPicker, { type PickerItem } from "../../components/EntityPicker";
import ImageUploadField from "../../components/ImageUploadField";
import ContributorGate from "../../components/ContributorGate";
import EditNoteField from "../../components/EditNoteField";
import EditSavedBanner from "../../components/EditSavedBanner";
import ClearedFieldsPrompt from "../../components/ClearedFieldsPrompt";
import { findClearedFields, type ClearedField } from "../../lib/clearedFields";
import { WORLD_LANGUAGES } from "../../lib/languages";

const inputCls =
  "w-full border border-gray-200 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-violet-500";
const labelCls = "block text-xs font-semibold text-gray-500 mb-1";

const FORMAT_TYPES = ["paperback", "hardcover", "ebook"];

const AVAILABILITY_OPTIONS = [
  { value: "", label: "Unknown" },
  { value: "in_print", label: "In print" },
  { value: "out_of_print", label: "Out of print" },
  { value: "digital_only", label: "Digital only" },
  { value: "rare", label: "Rare" },
];

/** Inline-create a person (name only), auto-approved, returned as a picker item. */
async function createPersonInline(
  name: string,
  opts?: { allowDuplicate?: boolean },
): Promise<PickerItem> {
  const sub = await volunteer.submitPerson({ name }, opts?.allowDuplicate);
  const entry = await admin.queue.review(sub.edit_id, true, "Direct admin entry");
  return { id: entry.record_id!, name };
}

/** Inline-create a publisher (name only), auto-approved, returned as a picker item. */
async function createPublisherInline(
  name: string,
  opts?: { allowDuplicate?: boolean },
): Promise<PickerItem> {
  const sub = await volunteer.submitPublisher({ name }, opts?.allowDuplicate);
  const entry = await admin.queue.review(sub.edit_id, true, "Direct admin entry");
  return { id: entry.record_id!, name };
}

export default function AdminEditBook() {
  const { id } = useParams<{ id: string }>();
  const { data: work, isLoading } = useQuery({
    queryKey: ["work", id],
    queryFn: () => works.get(Number(id)),
    enabled: !!id,
  });

  if (isLoading) {
    return <div className="text-gray-400 py-12 text-center">Loading book…</div>;
  }
  if (!work) {
    return <div className="text-gray-400 py-12 text-center">Book not found.</div>;
  }
  if (work.type !== "BOOK") {
    return (
      <div className="text-gray-400 py-12 text-center">
        Only BOOK works can be edited here (this is {work.type}).
      </div>
    );
  }
  return (
    <ContributorGate>
      <EditForm key={work.id} work={work} />
    </ContributorGate>
  );
}

function EditForm({ work }: { work: WorkDetail }) {
  const qc = useQueryClient();
  const { user } = useAuth();
  const isAdmin = user?.role.toLowerCase() === "admin";
  const [note, setNote] = useState("");
  const { data: allGenres } = useQuery({ queryKey: ["all-genres"], queryFn: catalogue.allGenres });
  const { data: allTags } = useQuery({ queryKey: ["all-tags"], queryFn: catalogue.allTags });
  const { data: seriesPage } = useQuery({ queryKey: ["all-series"], queryFn: catalogue.series });
  const { data: languages } = useQuery({
    queryKey: ["all-languages"],
    queryFn: catalogue.allLanguages,
  });
  const seriesList = seriesPage?.items ?? [];

  const [title, setTitle] = useState(work.title);
  const [description, setDescription] = useState(work.description ?? "");
  const [language, setLanguage] = useState(work.language ?? "bn");
  // Romanised (Latin) title — auto-generated by the backend, editable here. Keyed by
  // the work's original language ('{lang}-Latn'). Editing it pins a manual override.
  const initialRoman = work.localised?.title?.[`${work.language ?? "bn"}-Latn`] ?? "";
  const [roman, setRoman] = useState(initialRoman);
  const [originalLanguage, setOriginalLanguage] = useState(work.original_language ?? "");
  const [year, setYear] = useState(
    work.book?.publication_year?.toString() ??
      (work.publication_date ? work.publication_date.slice(0, 4) : "")
  );
  const [authors, setAuthors] = useState<PickerItem[]>(
    work.authors.map((a) => ({ id: a.id, name: a.name }))
  );
  const [editors, setEditors] = useState<PickerItem[]>(
    (work.book?.editors ?? []).map((p) => ({ id: p.id, name: p.name }))
  );
  const [illustrators, setIllustrators] = useState<PickerItem[]>(
    (work.book?.illustrators ?? []).map((p) => ({ id: p.id, name: p.name }))
  );
  const [translators, setTranslators] = useState<PickerItem[]>(
    (work.book?.translators ?? []).map((p) => ({ id: p.id, name: p.name }))
  );
  const [coverArtists, setCoverArtists] = useState<PickerItem[]>(
    (work.book?.cover_artists ?? []).map((p) => ({ id: p.id, name: p.name }))
  );
  const [publishers, setPublishers] = useState<PickerItem[]>(
    (work.book?.publishers ?? []).map((p) => ({ id: p.id, name: p.name }))
  );
  const [genreIds, setGenreIds] = useState<Set<number>>(
    new Set(work.genres.map((g) => g.id))
  );
  const [coverUrl, setCoverUrl] = useState(
    work.image_urls?.[0] ?? work.book?.formats?.[0]?.cover_image_url ?? ""
  );
  const [tagIds, setTagIds] = useState<Set<number>>(new Set(work.tags.map((t) => t.id)));
  const [seriesId, setSeriesId] = useState(work.book?.series_id?.toString() ?? "");
  const [seriesPosition, setSeriesPosition] = useState(
    work.book?.series_position?.toString() ?? ""
  );
  const [editionLabel, setEditionLabel] = useState(work.book?.edition_label ?? "");
  const [editionNotes, setEditionNotes] = useState(work.book?.edition_notes ?? "");
  const firstFormat = work.book?.formats?.[0] ?? null;
  const [formatType, setFormatType] = useState(firstFormat?.format_type ?? "paperback");
  const [isbn, setIsbn] = useState(firstFormat?.isbn ?? "");
  const [pageCount, setPageCount] = useState(firstFormat?.page_count?.toString() ?? "");
  const [availability, setAvailability] = useState(firstFormat?.availability ?? "");
  const [saved, setSaved] = useState(false);
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [pendingClears, setPendingClears] = useState<ClearedField[] | null>(null);
  const navigate = useNavigate();

  const deleteMutation = useMutation({
    mutationFn: () => admin.works.delete(work.id),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["works"] });
      qc.invalidateQueries({ queryKey: ["genres"] });
      qc.removeQueries({ queryKey: ["work", String(work.id)] });
      navigate("/admin/tagging");
    },
  });

  const mutation = useMutation({
    mutationFn: async () => {
      const y = year ? Number(year) : null;

      // Replace-semantics: edit the first format in place (preserving fields the
      // form doesn't expose) and pass any further formats through untouched.
      let formats: BookUpdateIn["formats"];
      if (firstFormat || isbn.trim() || pageCount || availability) {
        formats = [
          {
            format_type: formatType,
            isbn: isbn.trim() || null,
            page_count: pageCount ? Number(pageCount) : null,
            availability: availability || null,
            publication_date: firstFormat?.publication_date ?? null,
            cover_image_url: firstFormat?.cover_image_url ?? null,
            price: firstFormat?.price ?? null,
            currency: firstFormat?.currency ?? null,
            notes: firstFormat?.notes ?? null,
          },
          ...(work.book?.formats ?? []).slice(1).map((f) => ({
            format_type: f.format_type,
            isbn: f.isbn,
            page_count: f.page_count,
            availability: f.availability,
            publication_date: f.publication_date,
            cover_image_url: f.cover_image_url,
            price: f.price,
            currency: f.currency,
            notes: f.notes,
          })),
        ];
      }

      // Only send the romanisation when it was actually edited — otherwise leave it to
      // the backend's auto-romaniser (sending it back would pin it as a manual override).
      const romanChanged = roman.trim() !== initialRoman.trim();
      const localised =
        romanChanged && roman.trim()
          ? { title: { [`${language}-Latn`]: roman.trim() } }
          : undefined;

      const sub = await volunteer.updateBook(work.id, {
        formats,
        title: title.trim(),
        description: description.trim() || null,
        language,
        localised,
        original_language: originalLanguage || null,
        publication_year: y,
        publication_date: y ? `${y}-01-01` : null,
        author_ids: authors.map((a) => a.id),
        editor_ids: editors.map((e) => e.id),
        illustrator_ids: illustrators.map((i) => i.id),
        translator_ids: translators.map((t) => t.id),
        cover_artist_ids: coverArtists.map((c) => c.id),
        publisher_ids: publishers.map((p) => p.id),
        genre_ids: [...genreIds],
        tag_ids: [...tagIds],
        series_id: seriesId ? Number(seriesId) : null,
        series_position: seriesPosition ? Number(seriesPosition) : null,
        edition_label: editionLabel.trim() || null,
        edition_notes: editionNotes.trim() || null,
        // empty list clears the work-level cover (null would mean "no change")
        image_urls: coverUrl.trim() ? [coverUrl.trim()] : [],
      }, isAdmin ? undefined : note);
      if (isAdmin) await admin.queue.review(sub.edit_id, true, "Direct admin edit");
      return sub;
    },
    onSuccess: () => {
      setSaved(true);
      setPendingClears(null);
      if (isAdmin) {
        qc.invalidateQueries({ queryKey: ["work", String(work.id)] });
        qc.invalidateQueries({ queryKey: ["works"] });
        qc.invalidateQueries({ queryKey: ["genres"] });
      }
    },
  });

  // Admin blanks clear the field; warn (once) before saving. Volunteers' blanks
  // are left unchanged by the backend, so no warning is needed.
  function attemptSave() {
    setSaved(false);
    if (!title.trim()) return;
    if (isAdmin) {
      const cleared = findClearedFields([
        { label: "Description", previous: work.description, next: description.trim() || null },
        {
          label: "Original language",
          previous: work.original_language,
          next: originalLanguage || null,
        },
        {
          label: "Publication year",
          previous: work.book?.publication_year,
          next: year ? Number(year) : null,
        },
        { label: "Edition label", previous: work.book?.edition_label, next: editionLabel.trim() || null },
        { label: "Edition notes", previous: work.book?.edition_notes, next: editionNotes.trim() || null },
        { label: "Cover image", previous: work.image_urls?.[0], next: coverUrl.trim() || null },
        { label: "ISBN", previous: firstFormat?.isbn, next: isbn.trim() || null },
        { label: "Pages", previous: firstFormat?.page_count, next: pageCount ? Number(pageCount) : null },
        { label: "Availability", previous: firstFormat?.availability, next: availability || null },
      ]);
      if (cleared.length) {
        setPendingClears(cleared);
        return;
      }
    }
    mutation.mutate();
  }

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault();
        attemptSave();
      }}
      className="max-w-2xl space-y-4"
    >
      <h1 className="text-xl font-bold text-gray-900">
        Edit Book
        <span className="ml-2 text-sm font-normal text-gray-400">#{work.id}</span>
      </h1>

      {pendingClears && (
        <ClearedFieldsPrompt
          fields={pendingClears}
          onConfirm={() => mutation.mutate()}
          onCancel={() => setPendingClears(null)}
          busy={mutation.isPending}
        />
      )}

      {saved && (
        <EditSavedBanner isAdmin={!!isAdmin} viewHref={`/works/${work.id}`} viewLabel="View book" />
      )}

      <div>
        <label className={labelCls}>Title *</label>
        <input value={title} onChange={(e) => setTitle(e.target.value)} required className={inputCls} />
      </div>

      {language !== "en" && (
        <div>
          <label className={labelCls}>Romanised title ({language}-Latn)</label>
          <input
            value={roman}
            onChange={(e) => setRoman(e.target.value)}
            placeholder="Auto-generated from the title — edit to override"
            className={inputCls}
          />
          <p className="mt-1 text-xs text-gray-400">
            Auto-generated for search. Leave blank/untouched to keep it auto-updating;
            editing pins your version so the auto-romaniser won’t overwrite it.
          </p>
        </div>
      )}

      <div>
        <label className={labelCls}>Description</label>
        <textarea
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          rows={3}
          className={inputCls}
        />
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-3 gap-4">
        <div>
          <label className={labelCls}>Language</label>
          <select value={language} onChange={(e) => setLanguage(e.target.value)} className={inputCls}>
            {(languages ?? [{ code: "bn", name: "Bengali", name_local: "বাংলা" }]).map((l) => (
              <option key={l.code} value={l.code}>
                {l.name}{l.name_local && l.name_local !== l.name ? ` (${l.name_local})` : ""}
              </option>
            ))}
          </select>
        </div>
        <div>
          <label className={labelCls}>Original language</label>
          <select
            value={originalLanguage}
            onChange={(e) => setOriginalLanguage(e.target.value)}
            className={inputCls}
          >
            <option value="">Not a translation</option>
            <optgroup label="World languages">
              {WORLD_LANGUAGES.map((l) => (
                <option key={l.code} value={l.code}>{l.name}</option>
              ))}
            </optgroup>
            <optgroup label="Indian languages">
              {(languages ?? [])
                .filter((l) => !WORLD_LANGUAGES.some((w) => w.code === l.code))
                .map((l) => (
                  <option key={l.code} value={l.code}>
                    {l.name}{l.name_local && l.name_local !== l.name ? ` (${l.name_local})` : ""}
                  </option>
                ))}
            </optgroup>
          </select>
        </div>
        <div>
          <label className={labelCls}>Publication year</label>
          <input
            type="number"
            min={1000}
            max={2100}
            value={year}
            onChange={(e) => setYear(e.target.value)}
            className={inputCls}
          />
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className={labelCls}>Edition label</label>
          <input
            value={editionLabel}
            onChange={(e) => setEditionLabel(e.target.value)}
            placeholder="e.g. First Edition, Revised"
            className={inputCls}
          />
        </div>
        <div>
          <label className={labelCls}>Edition notes</label>
          <input
            value={editionNotes}
            onChange={(e) => setEditionNotes(e.target.value)}
            className={inputCls}
          />
        </div>
      </div>

      {seriesList.length > 0 && (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <label className={labelCls}>Series</label>
            <select
              value={seriesId}
              onChange={(e) => setSeriesId(e.target.value)}
              className={inputCls}
            >
              <option value="">Not part of a series</option>
              {seriesList.map((s) => (
                <option key={s.id} value={s.id}>{s.name}</option>
              ))}
            </select>
          </div>
          <div>
            <label className={labelCls}>Position in series</label>
            <input
              type="number"
              min={1}
              value={seriesPosition}
              onChange={(e) => setSeriesPosition(e.target.value)}
              disabled={!seriesId}
              className={inputCls}
            />
          </div>
        </div>
      )}

      <ImageUploadField
        label="Cover image"
        category="covers"
        value={coverUrl}
        onChange={(url) => setCoverUrl(url ?? "")}
      />

      <EntityPicker
        label="Authors"
        placeholder="Search or create a person…"
        fetchKey="picker-persons"
        fetcher={(q) => catalogue.persons(q)}
        selected={authors}
        onChange={setAuthors}
        onCreate={isAdmin ? createPersonInline : undefined}
      />

      <EntityPicker
        label="Editors"
        placeholder="Search or create a person…"
        fetchKey="picker-persons"
        fetcher={(q) => catalogue.persons(q)}
        selected={editors}
        onChange={setEditors}
        onCreate={isAdmin ? createPersonInline : undefined}
      />

      <EntityPicker
        label="Translators"
        placeholder="Search or create a person…"
        fetchKey="picker-persons"
        fetcher={(q) => catalogue.persons(q)}
        selected={translators}
        onChange={setTranslators}
        onCreate={isAdmin ? createPersonInline : undefined}
      />

      <EntityPicker
        label="Illustrators"
        placeholder="Search or create a person…"
        fetchKey="picker-persons"
        fetcher={(q) => catalogue.persons(q)}
        selected={illustrators}
        onChange={setIllustrators}
        onCreate={isAdmin ? createPersonInline : undefined}
      />

      <EntityPicker
        label="Cover artists"
        placeholder="Search or create a person…"
        fetchKey="picker-persons"
        fetcher={(q) => catalogue.persons(q)}
        selected={coverArtists}
        onChange={setCoverArtists}
        onCreate={isAdmin ? createPersonInline : undefined}
      />

      <EntityPicker
        label="Publishers"
        placeholder="Search or create a publisher…"
        fetchKey="picker-publishers"
        fetcher={(q) => catalogue.publishers(q)}
        selected={publishers}
        onChange={setPublishers}
        onCreate={isAdmin ? createPublisherInline : undefined}
      />

      <div>
        <label className={labelCls}>Genres</label>
        <div className="flex flex-wrap gap-2">
          {(allGenres ?? []).map((g) => (
            <button
              key={g.id}
              type="button"
              onClick={() =>
                setGenreIds((prev) => {
                  const next = new Set(prev);
                  if (next.has(g.id)) next.delete(g.id);
                  else next.add(g.id);
                  return next;
                })
              }
              className={`text-xs px-2.5 py-1 rounded-full border transition-colors ${
                genreIds.has(g.id)
                  ? "bg-violet-700 text-white border-violet-700"
                  : "bg-white border-gray-300 text-gray-600 hover:border-violet-400"
              }`}
            >
              {g.genre_name}
            </button>
          ))}
        </div>
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <div>
          <label className={labelCls}>Format</label>
          <select value={formatType} onChange={(e) => setFormatType(e.target.value)} className={inputCls}>
            {FORMAT_TYPES.map((f) => (
              <option key={f} value={f}>{f.charAt(0).toUpperCase() + f.slice(1)}</option>
            ))}
            {firstFormat && !FORMAT_TYPES.includes(firstFormat.format_type) && (
              <option value={firstFormat.format_type}>{firstFormat.format_type}</option>
            )}
          </select>
        </div>
        <div>
          <label className={labelCls}>Pages</label>
          <input
            type="number"
            min={1}
            value={pageCount}
            onChange={(e) => setPageCount(e.target.value)}
            className={inputCls}
          />
        </div>
        <div>
          <label className={labelCls}>ISBN</label>
          <input value={isbn} onChange={(e) => setIsbn(e.target.value)} className={inputCls} />
        </div>
        <div>
          <label className={labelCls}>Availability</label>
          <select
            value={availability ?? ""}
            onChange={(e) => setAvailability(e.target.value)}
            className={inputCls}
          >
            {AVAILABILITY_OPTIONS.map((o) => (
              <option key={o.value} value={o.value}>{o.label}</option>
            ))}
          </select>
        </div>
      </div>

      {(allTags ?? []).length > 0 && (
        <div>
          <label className={labelCls}>Tags</label>
          <div className="flex flex-wrap gap-2">
            {(allTags ?? []).map((t) => (
              <button
                key={t.id}
                type="button"
                onClick={() =>
                  setTagIds((prev) => {
                    const next = new Set(prev);
                    if (next.has(t.id)) next.delete(t.id);
                    else next.add(t.id);
                    return next;
                  })
                }
                className={`text-xs px-2.5 py-1 rounded-full border transition-colors ${
                  tagIds.has(t.id)
                    ? "bg-violet-700 text-white border-violet-700"
                    : "bg-white border-gray-300 text-gray-600 hover:border-violet-400"
                }`}
              >
                {t.tag_name}
              </button>
            ))}
          </div>
        </div>
      )}

      <EditNoteField show={!isAdmin} value={note} onChange={setNote} />

      <div className="flex items-center gap-3 pt-2">
        <button
          type="submit"
          disabled={mutation.isPending}
          className="bg-violet-700 text-white text-sm px-5 py-2 rounded-md font-medium hover:bg-violet-800 disabled:opacity-40 transition-colors"
        >
          {mutation.isPending
            ? isAdmin
              ? "Saving…"
              : "Submitting…"
            : isAdmin
              ? "Save changes"
              : "Submit for review"}
        </button>
        <Link to={`/works/${work.id}`} className="text-sm text-gray-500 hover:text-gray-700">
          Cancel
        </Link>
        {mutation.isError && (
          <span className="text-sm text-red-500">Save failed — try again.</span>
        )}

        {isAdmin && (
          <button
            type="button"
            disabled={deleteMutation.isPending}
            onClick={() => {
              if (confirmDelete) deleteMutation.mutate();
              else setConfirmDelete(true);
            }}
            onBlur={() => setConfirmDelete(false)}
            className={`ml-auto text-sm px-4 py-2 rounded-md border transition-colors disabled:opacity-40 ${
              confirmDelete
                ? "bg-red-600 text-white border-red-600 hover:bg-red-700"
                : "border-red-300 text-red-600 hover:bg-red-50"
            }`}
          >
            {deleteMutation.isPending
              ? "Deleting…"
              : confirmDelete
                ? "Click again to permanently delete"
                : "Delete book"}
          </button>
        )}
        {isAdmin && deleteMutation.isError && (
          <span className="text-sm text-red-500">Delete failed.</span>
        )}
      </div>
    </form>
  );
}
