import { useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { admin, ApiError, catalogue, volunteer, works, type WorkDetail, type BookUpdateIn } from "../../lib/api";
import { useAuth } from "../../hooks/useAuth";
import EntityPicker, { type PickerItem } from "../../components/EntityPicker";
import BylineFields, { bylinePayload } from "../../components/BylineFields";
import FormatsEditor, {
  type FormatRow,
  formatRowsFromExisting,
  formatRowsToPayload,
} from "../../components/FormatsEditor";
import TranslationLinksEditor from "../../components/TranslationLinksEditor";
import AwardsEditor from "../../components/AwardsEditor";
import ExternalLinksEditor from "../../components/ExternalLinksEditor";
import WorkRelationshipsEditor from "../../components/WorkRelationshipsEditor";
import SourceAttributionFields, {
  type SourceAttribution,
  sourceAttributionPayload,
} from "../../components/SourceAttributionFields";
import ImageUploadField from "../../components/ImageUploadField";
import FormSection from "../../components/FormSection";
import TagChipPicker from "../../components/TagChipPicker";
import ContributorGate from "../../components/ContributorGate";
import EditNoteField from "../../components/EditNoteField";
import EditSavedBanner from "../../components/EditSavedBanner";
import ClearedFieldsPrompt from "../../components/ClearedFieldsPrompt";
import { findClearedFields, type ClearedField } from "../../lib/clearedFields";
import { WORLD_LANGUAGES } from "../../lib/languages";
import { WORK_TYPE_OPTIONS } from "../../lib/workTypes";
import { createPersonInline, createPublisherInline } from "../../lib/inlineCreate";

const inputCls =
  "w-full border border-gray-200 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-violet-500";
const labelCls = "block text-xs font-semibold text-gray-500 mb-1";

export default function AdminEditBook() {
  const { id } = useParams<{ id: string }>();
  const { data: work, isLoading } = useQuery({
    queryKey: ["work", id],
    queryFn: () => works.get(Number(id)),
    enabled: !!id,
  });

  if (isLoading) {
    return <div className="text-gray-400 py-12 text-center">Loading book…</div>;
  }
  if (!work) {
    return <div className="text-gray-400 py-12 text-center">Book not found.</div>;
  }
  if (work.type !== "BOOK") {
    return (
      <div className="text-gray-400 py-12 text-center">
        Only BOOK works can be edited here (this is {work.type}).
      </div>
    );
  }
  return (
    <ContributorGate>
      <EditForm key={work.id} work={work} />
    </ContributorGate>
  );
}

function EditForm({ work }: { work: WorkDetail }) {
  const qc = useQueryClient();
  const { user } = useAuth();
  const isAdmin = user?.role.toLowerCase() === "admin";
  const canInlineCreate = isAdmin || !!user?.auto_approve;
  const [note, setNote] = useState("");
  const { data: allGenres } = useQuery({ queryKey: ["all-genres"], queryFn: catalogue.allGenres });
  const { data: seriesPage } = useQuery({ queryKey: ["all-series"], queryFn: catalogue.series });
  const { data: languages } = useQuery({
    queryKey: ["all-languages"],
    queryFn: catalogue.allLanguages,
  });
  const seriesList = seriesPage?.items ?? [];

  const [title, setTitle] = useState(work.title);
  const [description, setDescription] = useState(work.description ?? "");
  const [language, setLanguage] = useState(work.language ?? "bn");
  const [contentType, setContentType] = useState(work.content_type ?? "");
  // Romanised (Latin) title — auto-generated by the backend, editable here. Keyed by
  // the work's original language ('{lang}-Latn'). Editing it pins a manual override.
  const initialRoman = work.localised?.title?.[`${work.language ?? "bn"}-Latn`] ?? "";
  const [roman, setRoman] = useState(initialRoman);
  const [originalLanguage, setOriginalLanguage] = useState(work.original_language ?? "");
  const [year, setYear] = useState(
    work.book?.publication_year?.toString() ??
      (work.publication_date ? work.publication_date.slice(0, 4) : "")
  );
  const [authors, setAuthors] = useState<PickerItem[]>(
    work.authors.map((a) => ({ id: a.id, name: a.name }))
  );
  // Byline overrides per credited person ("credited as", e.g. a pen name).
  // One map for the whole work: a byline applies to every role that person holds.
  const [bylines, setBylines] = useState<Record<number, string>>(() => {
    const init: Record<number, string> = {};
    const credits = [
      ...work.authors,
      ...(work.book?.editors ?? []),
      ...(work.book?.translators ?? []),
      ...(work.book?.illustrators ?? []),
      ...(work.book?.cover_artists ?? []),
    ];
    for (const c of credits) if (c.credited_as && !init[c.id]) init[c.id] = c.credited_as;
    return init;
  });
  const [editors, setEditors] = useState<PickerItem[]>(
    (work.book?.editors ?? []).map((p) => ({ id: p.id, name: p.name }))
  );
  const [illustrators, setIllustrators] = useState<PickerItem[]>(
    (work.book?.illustrators ?? []).map((p) => ({ id: p.id, name: p.name }))
  );
  const [translators, setTranslators] = useState<PickerItem[]>(
    (work.book?.translators ?? []).map((p) => ({ id: p.id, name: p.name }))
  );
  const [coverArtists, setCoverArtists] = useState<PickerItem[]>(
    (work.book?.cover_artists ?? []).map((p) => ({ id: p.id, name: p.name }))
  );
  const [publishers, setPublishers] = useState<PickerItem[]>(
    (work.book?.publishers ?? []).map((p) => ({ id: p.id, name: p.name }))
  );
  const [genreIds, setGenreIds] = useState<Set<number>>(
    new Set(work.genres.map((g) => g.id))
  );
  const [coverUrl, setCoverUrl] = useState(
    work.image_urls?.[0] ?? work.book?.formats?.[0]?.cover_image_url ?? ""
  );
  const [tagIds, setTagIds] = useState<Set<number>>(new Set(work.tags.map((t) => t.id)));
  const [seriesId, setSeriesId] = useState(work.book?.series_id?.toString() ?? "");
  const [seriesPosition, setSeriesPosition] = useState(
    work.book?.series_position?.toString() ?? ""
  );
  const [editionLabel, setEditionLabel] = useState(work.book?.edition_label ?? "");
  const [editionNotes, setEditionNotes] = useState(work.book?.edition_notes ?? "");
  const [formats, setFormats] = useState<FormatRow[]>(
    formatRowsFromExisting(work.book?.formats)
  );
  const [source, setSource] = useState<SourceAttribution>({
    original_title: work.book?.original_title ?? "",
    original_author: work.book?.original_author ?? "",
    source_relation: work.book?.source_relation ?? "",
  });
  const [saved, setSaved] = useState(false);
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [pendingClears, setPendingClears] = useState<ClearedField[] | null>(null);
  const navigate = useNavigate();

  const deleteMutation = useMutation({
    mutationFn: () => admin.works.delete(work.id),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["works"] });
      qc.invalidateQueries({ queryKey: ["genres"] });
      qc.removeQueries({ queryKey: ["work", String(work.id)] });
      navigate("/admin/tagging");
    },
  });

  const mutation = useMutation({
    mutationFn: async () => {
      const y = year ? Number(year) : null;

      // Replace-semantics: send the full format list (keeping detail-less existing
      // rows). An empty list clears all formats; an unchanged list is a no-op.
      const formatsPayload: BookUpdateIn["formats"] = formatRowsToPayload(formats, true);

      // Only send the romanisation when it was actually edited — otherwise leave it to
      // the backend's auto-romaniser (sending it back would pin it as a manual override).
      const romanChanged = roman.trim() !== initialRoman.trim();
      const localised =
        romanChanged && roman.trim()
          ? { title: { [`${language}-Latn`]: roman.trim() } }
          : undefined;

      const sub = await volunteer.updateBook(work.id, {
        formats: formatsPayload,
        title: title.trim(),
        description: description.trim() || null,
        content_type: contentType || null,
        language,
        localised,
        original_language: originalLanguage || null,
        publication_year: y,
        publication_date: y ? `${y}-01-01` : null,
        author_ids: authors.map((a) => a.id),
        credited_as: bylinePayload(
          [...authors, ...editors, ...translators, ...illustrators, ...coverArtists],
          bylines
        ),
        editor_ids: editors.map((e) => e.id),
        illustrator_ids: illustrators.map((i) => i.id),
        translator_ids: translators.map((t) => t.id),
        cover_artist_ids: coverArtists.map((c) => c.id),
        publisher_ids: publishers.map((p) => p.id),
        genre_ids: [...genreIds],
        tag_ids: [...tagIds],
        series_id: seriesId ? Number(seriesId) : null,
        series_position: seriesPosition ? Number(seriesPosition) : null,
        edition_label: editionLabel.trim() || null,
        edition_notes: editionNotes.trim() || null,
        ...sourceAttributionPayload(source),
        // empty list clears the work-level cover (null would mean "no change")
        image_urls: coverUrl.trim() ? [coverUrl.trim()] : [],
      }, isAdmin ? undefined : note);
      if (isAdmin) await admin.queue.review(sub.edit_id, true, "Direct admin edit");
      return sub;
    },
    onSuccess: () => {
      setSaved(true);
      setPendingClears(null);
      if (isAdmin) {
        qc.invalidateQueries({ queryKey: ["work", String(work.id)] });
        qc.invalidateQueries({ queryKey: ["works"] });
        qc.invalidateQueries({ queryKey: ["genres"] });
      }
    },
  });

  // Admin blanks clear the field; warn (once) before saving. Volunteers' blanks
  // are left unchanged by the backend, so no warning is needed.
  function attemptSave() {
    setSaved(false);
    if (!title.trim()) return;
    if (isAdmin) {
      const cleared = findClearedFields([
        { label: "Description", previous: work.description, next: description.trim() || null },
        {
          label: "Original language",
          previous: work.original_language,
          next: originalLanguage || null,
        },
        {
          label: "Publication year",
          previous: work.book?.publication_year,
          next: year ? Number(year) : null,
        },
        { label: "Edition label", previous: work.book?.edition_label, next: editionLabel.trim() || null },
        { label: "Edition notes", previous: work.book?.edition_notes, next: editionNotes.trim() || null },
        { label: "Cover image", previous: work.image_urls?.[0], next: coverUrl.trim() || null },
        {
          label: "Formats",
          previous: (work.book?.formats?.length ?? 0)
            ? `${work.book?.formats?.length} format(s)`
            : null,
          next: formatRowsToPayload(formats, true).length ? "set" : null,
        },
      ]);
      if (cleared.length) {
        setPendingClears(cleared);
        return;
      }
    }
    mutation.mutate();
  }

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault();
        attemptSave();
      }}
      className="max-w-2xl space-y-4"
    >
      <h1 className="text-xl font-bold text-gray-900">
        Edit Book
        <span className="ml-2 text-sm font-normal text-gray-400">#{work.id}</span>
      </h1>

      {saved && (
        <EditSavedBanner isAdmin={!!isAdmin} viewHref={`/works/${work.id}`} viewLabel="View book" />
      )}

      <FormSection title="Basics">
      <div>
        <label className={labelCls}>Title * (native script preferred)</label>
        <input value={title} onChange={(e) => setTitle(e.target.value)} required className={inputCls} />
      </div>

      {language !== "en" && (
        <div>
          <label className={labelCls}>Romanised title ({language}-Latn)</label>
          <input
            value={roman}
            onChange={(e) => setRoman(e.target.value)}
            placeholder="Auto-generated from the title — edit to override"
            className={inputCls}
          />
          <p className="mt-1 text-xs text-gray-400">
            Auto-generated for search. Leave blank/untouched to keep it auto-updating;
            editing pins your version so the auto-romaniser won’t overwrite it.
          </p>
        </div>
      )}

      <div>
        <label className={labelCls}>Description</label>
        <textarea
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          rows={3}
          className={inputCls}
        />
      </div>
      </FormSection>

      <FormSection title="Publication details">
      <div className="grid grid-cols-2 sm:grid-cols-3 gap-4">
        <div>
          <label className={labelCls}>Work type</label>
          <select
            value={contentType}
            onChange={(e) => setContentType(e.target.value)}
            className={inputCls}
          >
            <option value="">Unspecified</option>
            {WORK_TYPE_OPTIONS.map((o) => (
              <option key={o.value} value={o.value}>
                {o.label}
              </option>
            ))}
          </select>
        </div>
        <div>
          <label className={labelCls}>Language</label>
          <select value={language} onChange={(e) => setLanguage(e.target.value)} className={inputCls}>
            {(languages ?? [{ code: "bn", name: "Bengali", name_local: "বাংলা" }]).map((l) => (
              <option key={l.code} value={l.code}>
                {l.name}{l.name_local && l.name_local !== l.name ? ` (${l.name_local})` : ""}
              </option>
            ))}
          </select>
        </div>
        <div>
          <label className={labelCls}>Original language (if translation)</label>
          <select
            value={originalLanguage}
            onChange={(e) => setOriginalLanguage(e.target.value)}
            className={inputCls}
          >
            <option value="">Not a translation</option>
            <optgroup label="World languages">
              {WORLD_LANGUAGES.map((l) => (
                <option key={l.code} value={l.code}>{l.name}</option>
              ))}
            </optgroup>
            <optgroup label="Indian languages">
              {(languages ?? [])
                .filter((l) => !WORLD_LANGUAGES.some((w) => w.code === l.code))
                .map((l) => (
                  <option key={l.code} value={l.code}>
                    {l.name}{l.name_local && l.name_local !== l.name ? ` (${l.name_local})` : ""}
                  </option>
                ))}
            </optgroup>
          </select>
        </div>
        <div>
          <label className={labelCls}>Publication year</label>
          <input
            type="number"
            min={1000}
            max={2100}
            value={year}
            onChange={(e) => setYear(e.target.value)}
            className={inputCls}
          />
        </div>
      </div>

      {seriesList.length > 0 && (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <label className={labelCls}>Series</label>
            <select
              value={seriesId}
              onChange={(e) => setSeriesId(e.target.value)}
              className={inputCls}
            >
              <option value="">Not part of a series</option>
              {seriesList.map((s) => (
                <option key={s.id} value={s.id}>{s.name}</option>
              ))}
            </select>
          </div>
          <div>
            <label className={labelCls}>Position in series</label>
            <input
              type="number"
              min={1}
              value={seriesPosition}
              onChange={(e) => setSeriesPosition(e.target.value)}
              disabled={!seriesId}
              className={inputCls}
            />
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className={labelCls}>Edition label</label>
          <input
            value={editionLabel}
            onChange={(e) => setEditionLabel(e.target.value)}
            placeholder="e.g. First Edition, Revised"
            className={inputCls}
          />
        </div>
        <div>
          <label className={labelCls}>Edition notes</label>
          <input
            value={editionNotes}
            onChange={(e) => setEditionNotes(e.target.value)}
            className={inputCls}
          />
        </div>
      </div>
      </FormSection>

      <FormSection
        title="Formats"
        hint="Hardcover / paperback / ebook / audiobook releases of this edition."
      >
        <FormatsEditor value={formats} onChange={setFormats} />
      </FormSection>

      <FormSection
        title="People & credits"
        hint="Search existing people, or type a new name to create them inline."
      >
      <EntityPicker
        label="Authors"
        placeholder="Search or create a person…"
        fetchKey="picker-persons"
        fetcher={(q) => catalogue.personPicker(q)}
        selected={authors}
        onChange={setAuthors}
        onCreate={canInlineCreate ? createPersonInline : undefined}
      />
      <BylineFields people={authors} bylines={bylines} onChange={setBylines} admin />

      <EntityPicker
        label="Editors"
        placeholder="Search or create a person…"
        fetchKey="picker-persons"
        fetcher={(q) => catalogue.personPicker(q)}
        selected={editors}
        onChange={setEditors}
        onCreate={canInlineCreate ? createPersonInline : undefined}
      />
      <BylineFields people={editors} bylines={bylines} onChange={setBylines} admin />

      <EntityPicker
        label="Translators"
        placeholder="Search or create a person…"
        fetchKey="picker-persons"
        fetcher={(q) => catalogue.personPicker(q)}
        selected={translators}
        onChange={setTranslators}
        onCreate={canInlineCreate ? createPersonInline : undefined}
      />
      <BylineFields people={translators} bylines={bylines} onChange={setBylines} admin />

      <EntityPicker
        label="Illustrators"
        placeholder="Search or create a person…"
        fetchKey="picker-persons"
        fetcher={(q) => catalogue.personPicker(q)}
        selected={illustrators}
        onChange={setIllustrators}
        onCreate={canInlineCreate ? createPersonInline : undefined}
      />
      <BylineFields people={illustrators} bylines={bylines} onChange={setBylines} admin />

      <EntityPicker
        label="Cover artists"
        placeholder="Search or create a person…"
        fetchKey="picker-persons"
        fetcher={(q) => catalogue.personPicker(q)}
        selected={coverArtists}
        onChange={setCoverArtists}
        onCreate={canInlineCreate ? createPersonInline : undefined}
      />
      <BylineFields people={coverArtists} bylines={bylines} onChange={setBylines} admin />

      <EntityPicker
        label="Publishers"
        placeholder="Search or create a publisher…"
        fetchKey="picker-publishers"
        fetcher={(q) => catalogue.publishers(q)}
        selected={publishers}
        onChange={setPublishers}
        onCreate={canInlineCreate ? createPublisherInline : undefined}
      />
      </FormSection>

      <FormSection
        title="Source & translations"
        hint="An uncatalogued source as free text, or links to catalogued translations/originals."
      >
      <SourceAttributionFields value={source} onChange={setSource} />

      <TranslationLinksEditor
        workId={work.id}
        workLanguage={work.language}
        isAdmin={!!isAdmin}
      />
      </FormSection>

      <FormSection
        title="Related works"
        hint="Link sequels, prequels, spin-offs, retellings, or fix-ups. Saved immediately, separately from the fields above."
      >
        <WorkRelationshipsEditor work={work} />
      </FormSection>

      <FormSection title="Cover & classification">
      <ImageUploadField
        label="Cover image"
        category="covers"
        value={coverUrl}
        onChange={(url) => setCoverUrl(url ?? "")}
      />

      <div>
        <label className={labelCls}>Genres</label>
        <div className="flex flex-wrap gap-2">
          {(allGenres ?? []).map((g) => (
            <button
              key={g.id}
              type="button"
              onClick={() =>
                setGenreIds((prev) => {
                  const next = new Set(prev);
                  if (next.has(g.id)) next.delete(g.id);
                  else next.add(g.id);
                  return next;
                })
              }
              className={`text-xs px-2.5 py-1 rounded-full border transition-colors ${
                genreIds.has(g.id)
                  ? "bg-violet-700 text-white border-violet-700"
                  : "bg-white border-gray-300 text-gray-600 hover:border-violet-400"
              }`}
            >
              {g.genre_name}
            </button>
          ))}
        </div>
      </div>

      <TagChipPicker selected={tagIds} onChange={setTagIds} />
      </FormSection>

      <FormSection
        title="Awards & external links"
        hint="Saved immediately, separately from the fields above — no need to click Save."
      >
        <AwardsEditor target={{ kind: "work", id: work.id }} isAdmin={!!isAdmin} />
        <ExternalLinksEditor
          target={{ kind: "work", id: work.id }}
          links={work.external_links}
          isAdmin={!!isAdmin}
        />
      </FormSection>

      <EditNoteField show={!isAdmin} value={note} onChange={setNote} />

      {pendingClears && (
        <ClearedFieldsPrompt
          fields={pendingClears}
          onConfirm={() => mutation.mutate()}
          onCancel={() => setPendingClears(null)}
          busy={mutation.isPending}
        />
      )}

      <div className="flex items-center gap-3 pt-2">
        <button
          type="submit"
          disabled={mutation.isPending}
          className="bg-violet-700 text-white text-sm px-5 py-2 rounded-md font-medium hover:bg-violet-800 disabled:opacity-40 transition-colors"
        >
          {mutation.isPending
            ? isAdmin
              ? "Saving…"
              : "Submitting…"
            : isAdmin
              ? "Save changes"
              : "Submit for review"}
        </button>
        <Link to={`/works/${work.id}`} className="text-sm text-gray-500 hover:text-gray-700">
          Cancel
        </Link>
        {mutation.isError && (
          <span className="text-sm text-red-500">Save failed — try again.</span>
        )}

        {isAdmin && (
          <button
            type="button"
            disabled={deleteMutation.isPending}
            onClick={() => {
              if (confirmDelete) deleteMutation.mutate();
              else setConfirmDelete(true);
            }}
            onBlur={() => setConfirmDelete(false)}
            className={`ml-auto text-sm px-4 py-2 rounded-md border transition-colors disabled:opacity-40 ${
              confirmDelete
                ? "bg-red-600 text-white border-red-600 hover:bg-red-700"
                : "border-red-300 text-red-600 hover:bg-red-50"
            }`}
          >
            {deleteMutation.isPending
              ? "Deleting…"
              : confirmDelete
                ? "Click again to permanently delete"
                : "Delete book"}
          </button>
        )}
        {isAdmin && deleteMutation.isError && (
          <span className="text-sm text-red-500">
            {deleteMutation.error instanceof ApiError
              ? deleteMutation.error.message
              : "Delete failed."}
          </span>
        )}
      </div>
    </form>
  );
}
